Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -37,7 +37,11 @@ jobs:
           -H "Accept: application/vnd.github+json"
           -H "X-GitHub-Api-Version: 2022-11-28"
           "https://api.github.com/repos/solar-owl/Practice_SDET_UI/actions/artifacts?names=allure-results"
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);"
+          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']  if data['artifacts'] else '');"
+          if [ -z "$ARTIFACT_ID" ]; then
+            echo "Error: Artifact 'allure-results' not found"
+            exit 1
+          fi
       - run: >
           ARTIFACT_ID=$(curl -L
           -H "Accept: application/vnd.github+json"
